### ISSUE TITLE
More export formats

### ISSUE THREAD

**Issue by 25A0** [25A0/Quadtastic#1]
Currently Quadtastic can only export quads as a .lua table. That was its primary use case, and makes sense for LOVE projects, but adding other output formats might make Quadtastic useful for other dev environments, too.

If you would like to see a specific export format added to Quadtastic, let me know below.

**Comment by RafaelOliveira** [comment]
Hi, I just found Quadtastic in Itch.io. I don't use LOVE, but I liked the tool. Currently I made my sprites in Gimp, and I use a plugin that I made to export the layers like Quadtastic do. With Quadtastic I would avoid the use of the gimp file, and use a png file in any editor.

Below is a example of the format I use in my engine. The format is: quad_name;x_position;y_position;width;height

shot_enemy;44;5;2;2
shot_ship;38;5;5;5
turbine_base_hor;38;1;9;3
turbine_base_vert;34;1;3;9
turbine_base_diag;34;11;9;9
turbine_hor;34;21;22;13
turbine_vert;57;19;13;22
turbine_diag;57;1;18;17
ship;1;1;32;32

It's a personal engine, but I think it's simple enough that could be used by other people, it just need to read line by line and divide the line with semicolon. I saw it's possible to group the quads, I don't use this, but to be complete, it could be something like:

shot_enemy;44;5;2;2
shot_ship;38;5;5;5
group turbine
turbine_base_hor;38;1;9;3
turbine_base_vert;34;1;3;9
turbine_base_diag;34;11;9;9
turbine_hor;34;21;22;13
endgroup
turbine_vert;57;19;13;22
turbine_diag;57;1;18;17
ship;1;1;32;32

the word group would start the group with the name in the side, and the word endgroup would finish. But this is just a suggestion to maintain the style very simple.

**Comment by aloisdeniel** [comment]
The first step could be common format like json and xml.

It could be great for [Monogame](http://www.monogame.net/) too !

Exporting as a C# class for example :
```csharp
public class Atlas
{
    public static readonly int[] Base = { 0, 0, 16, 32 };

    public static readonly int[][] Bubbles = 
    { 
	new [] {16, 16, 32, 32},
	new [] {32, 16, 32, 32},
    };
}
```

**Comment by 25A0** [comment]
Thanks for the feedback and ideas!

Common formats like json and xml are definitely a good idea. I'm also planning to allow users to write and use their own exporter (or use a custom exporter that someone else wrote). It could be cool to have a small, curated collection of custom exporters in this repo.

**Comment by 25A0** [comment]
Ok, I'm nearly done with this feature (see #9).

@aloisdeniel, I like your idea to export quad definitions as classes. This way you could check at compile time which quads are available (in most cases), and that's kind of neat. I'll try to write an exporter for that.

I don't have any experience with C# in particular though, and I'd be grateful for your input for one question: What would be a good way to represent groups of named quads? Nested public classes?

If it's not clear, here is what I have in mind: Say you have these quads:
```lua
{
  ["a group"] = {
    ["first quad"] = {x = 4, y = 12, w = 4, h = 8},
    ["second quad"] = {x = 8, y = 12, w = 4, h = 8},
  },
  ["a quad"] = {x = 4, y = 4, w = 8, h = 8},
}
```

I was thinking that you could represent this structure like so:
```C#
public class Quads
{
    public class A_Group
    {
        public static readonly int[] first_quad = {4, 12, 4, 8};
        public static readonly int[] second_quad = {8, 12, 4, 8};
    }

    public static readonly int[] a_quad = {4, 4, 8, 8};
}
```
What do you think?
