### ISSUE TITLE
Quadtastic.app is eager to open all ".love" archives

### ISSUE THREAD

**Issue by 25A0** [25A0/Quadtastic#21]
Quadtastic is listed amongst the apps that can open files with the extension ".love", probably because I didn't remove the elements of [`CFBundleDocumentTypes`](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html) in `info.plist`.

---
Affects: macOS

**Comment by fluffy-critter** [comment]
Ah, I see that you already know this issue. I guess you can disregard my itch.io community post :)
