### ISSUE TITLE
Sort file selector

### ISSUE THREAD

**Issue by fluffy-critter** [25A0/Quadtastic#24]
The `file...open` dialog box just seems to show the files in the order as presented by the filesystem, which on macOS can end up being pretty much random. It'd be nice if it were sorted alphabetically (ideally case-insensitive).

**Comment by 25A0** [comment]
Weird.. I'm on macOS and it's sorted alphabetically (case-insensitive).
I'll look into it.

**Comment by fluffy-critter** [comment]
Ah, it seems to be an APFS thing - my iMac running Sierra shows everything in order, but my MacBook running the High Sierra developer preview has everything weird.

**Comment by 25A0** [comment]
Could you check if 6fa7ee333faabc447b0ac233bde7b3be0d5b5e6a fixed this issue for you?
Let me know if you have trouble running Quadtastic from source :) in that case I can upload a binary build.

**Comment by fluffy-critter** [comment]
I had no trouble running from source. :) That change fixes it, thanks!

**Comment by 25A0** [comment]
Excellent. Thanks for testing!
