### ISSUE TITLE
Errors in the documentation

### ISSUE THREAD

**Issue by oneraul** [25A0/Quadtastic#7]
I've found a few errors in the _[Using quads and palettes](https://github.com/25A0/Quadtastic/wiki/Using-quads-and-palettes)_ page of the wiki.

Mainly, the functions `libquadtastic.import_quads` and `libquadtastic.import_palette` don't exist in the library. Browsing the source I guess they must be `libquadtastic.create_quads` and `libquadtastic.create_palette`.

Also the function `love.graphics.newSpritebatch` should be `love.graphics.newSpriteBatch`, with capital B.

They are minor things, but make the example code useless.

**Comment by 25A0** [comment]
I fixed the errors and extended the documentation a bit.
Thanks for reporting! :)
